// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCloneCompare() {
  return window['go']['main']['App']['CancelCloneCompare']();
}

export function CancelEmailCopy() {
  return window['go']['main']['App']['CancelEmailCopy']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckOutputExists(arg1) {
  return window['go']['main']['App']['CheckOutputExists'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetScanDefaults() {
  return window['go']['main']['App']['GetScanDefaults']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function RestartToApplyUpdate() {
  return window['go']['main']['App']['RestartToApplyUpdate']();
}

export function ResumeCloneWithDriveB(arg1) {
  return window['go']['main']['App']['ResumeCloneWithDriveB'](arg1);
}

export function SaveReleaseFolder(arg1) {
  return window['go']['main']['App']['SaveReleaseFolder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartCloneCompare(arg1) {
  return window['go']['main']['App']['StartCloneCompare'](arg1);
}

export function StartEmailCopy(arg1, arg2) {
  return window['go']['main']['App']['StartEmailCopy'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function ValidateScanPaths(arg1, arg2) {
  return window['go']['main']['App']['ValidateScanPaths'](arg1, arg2);
}
